AllCops:
    Exclude:
        - 'lib/rpg_lib/parser/dice_expression_parser.rb'

Metrics/LineLength:
    Enabled: false
Metrics/ModuleLength:
    Enabled: false
Metrics/BlockLength:
    Enabled: true
    Exclude:
        - res/*.rb
        - spec/**/*.rb
